---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-one
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-one
  template:
    metadata:
      labels:
        app: service-one
    spec:
      containers:
      - name: service-one
        image: 192.168.49.2:30400/service-one
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker