---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul:1.7.3
        ports:
        - containerPort: 8500
        - containerPort: 8600
        command:
        - consul
        - agent
        - -server
        - -client=0.0.0.0
        - -ui
        - -bootstrap-expect=1
        - -data-dir=/consul/data
        - -datacenter=blr
        volumeMounts:
        - name: consuldata
          mountPath: /consul/data
      volumes:
      - name: consuldata
        emptyDir: {}