---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-two
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-two
  template:
    metadata:
      labels:
        app: service-two
    spec:
      containers:
      - name: service-two
        image: 192.168.49.2:30400/service-two
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker